language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.5.0
  - jruby-head
  - ruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-9.0.5.0
    - rvm: truffleruby
env:
  global:
    - SQLITE_BUILD_WORKDIR=sqlite_build
  matrix:
    - SQLITE_VERSION=3.6.10
    - SQLITE_VERSION=3.19.4
    - SQLITE_VERSION=3.27.2
cache:
  directories:
    - sqlite_build
before_install:
  - gem install bundler || gem install bundler --version '< 2'
  - ./sqlite-build $SQLITE_VERSION
  - echo $(./sqlite-build env $SQLITE_VERSION)
  - export $(./sqlite-build env $SQLITE_VERSION)
  - gem env
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - mysql -e 'create database sequel_test;'
  - psql -c 'create database sequel_test;' -U postgres
addons:
  postgresql: "9.6"
services:
  - postgresql
